### ISSUE TITLE
Issue with Violentmonkey or userscript?

### ISSUE THREAD

**Issue by WesleyBryie** [GSRHackZ/Brainly-LockPick#1]
Just installed this, it does not work.
![image](https://github.com/GSRHackZ/Brainly-LockPick/assets/93141203/b1cb7709-0309-4a06-b857-8694541a0223)
![image](https://github.com/GSRHackZ/Brainly-LockPick/assets/93141203/845b2a27-052f-4053-839b-ab3de232eebc)

**Comment by GSRHackZ** [comment]
Has to be used with tampermonkey on chrome
